# Generated by Django 4.2.4 on 2023-08-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integer', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='', verbose_name='images/')),
            ],
        ),
    ]
