# Generated by Django 4.2.4 on 2023-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larisa', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
