# Generated by Django 4.2.4 on 2023-08-10 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d3c0281c-1c19-4a72-a401-1b60bcf37537'), editable=False, primary_key=True, serialize=False),
        ),
    ]
